export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const APP_LOAD = 'APP_LOAD';

/** USER AUTH */
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN = 'LOGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const LOGOUT = 'LOGOUT';
export const EMAIL_VALID = 'EMAIL_VALID'
export const EMAIL_INVALID = 'EMAIL_INVALID'

/** NOTES */
export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_LOADED_SUCCESS = 'NOTES_LOADED_SUCCESS';
export const NOTES_LOADED_FAILED = 'NOTES_LOADE_FAILED';
export const NOTE_DETAIL_LOADING = 'NOTE_DETAIL_LOADING';
export const NOTE_DETAIL_SUCCESS = 'NOTES_DETAIL_SUCESS';
export const NOTE_DETAIL_FAILED = 'NOTES_DETAIL_FAILED';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_FAILED = 'NOTE_UPDATE_FAILED';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAILED = 'NOTE_CREATE_FAILED';
// export const NOTE_CONTENT_CHANGED = 'NOTE_CONTENT_CHANGED';
// export const NOTE_TITLE_CHANGED = 'NOTE_TITLE_CHANGED';
